apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: basket
      context: src/basket
    - image: currency
      context: src/currency
    - image: notification
      context: src/notification
     - image: order
     context: src/order
     - image: payment
     context: src/payment
    - image: product-catalog
      context: src/product-catalog
    - image: shipment
      context: src/shipment

    - image: frontend
      context: src/frontend
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      - ./kubernetes/basket.yml
      - ./kubernetes/currency.yml
      - ./kubernetes/notification.yml
      - ./kubernetes/order.yml
      - ./kubernetes/payment.yml
      - ./kubernetes/product-catalog.yml
      - ./kubernetes/shipment.yml

      - ./kubernetes/frontend.yaml