basket-service-address: ${BASKET_SERVICE_ADDR:localhost}:8080
currency-service-address: ${CURRENCY_SERVICE_ADDR:localhost}:8081
notification-service-address: ${NOTIFICATION_SERVICE_ADDR:localhost}:8082
payment-service-address: ${PAYMENT_SERVICE_ADDR:localhost}:8084
product-catalog-service-address: ${PRODUCT_CATALOG_SERVICE_ADDR:localhost}:8085
shipping-service-address: ${SHIPPING_SERVICE_ADDR:localhost}:8086
