server:
    port: ${PORT:8084}

spring:
    datasource:
        url: jdbc:h2:mem:shipment
        driverClassName: org.h2.Driver
        username: sa
        password: password

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    cloud:
        gcp:
            sql:
                enabled: "false"