apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: product-catalog
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
              initialDelaySeconds: 3
              periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
              initialDelaySeconds: 3
              periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
spec:
  type: ClusterIP
  selector:
    app: product-catalog
  ports:
    - name: product_catalog_api_port
      port: 8085
      targetPort: 8085