apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment
spec:
  selector:
    matchLabels:
      app: shipment
  template:
    metadata:
      labels:
        app: shipment
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: shipment
          ports:
            - containerPort: 8086
          env:
            - name: PORT
              value: "8086"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
              initialDelaySeconds: 3
              periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
              initialDelaySeconds: 3
              periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: shipment
spec:
  type: ClusterIP
  selector:
    app: shipment
  ports:
    - name: shipment_api_port
      port: 8086
      targetPort: 8086