apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: basket
build:
  artifacts:
  - image: europe-central2-docker.pkg.dev/pwch-shop/pwch-shop-repository/basket
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./kubernetes/basket.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: europe-central2-docker.pkg.dev/pwch-shop/pwch-shop-repository/basket
      context: .
