apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: europe-central2-docker.pkg.dev/pwch-shop/pwch-shop-repository/product-catalog
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
spec:
  type: ClusterIP
  selector:
    app: product-catalog
  ports:
    - name: product-catalog-api-port
      port: 8085
      targetPort: 8085